# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-19 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, verbose_name='На складе'),
        ),
    ]
